services:
  api:
    build:
      context: ./tfprivate.Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    env_file:
      - .env
    networks:
      - tfprivate
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`modules.devopsfrontier.com`)
      - traefik.http.services.api.loadbalancer.server.port=80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/v1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  tfprivate:
    name: tfprivate
