name: Build and Validate

on:
  push:
    branches:
      - main
    paths:
      - "tfprivate.Api/**"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: ./tfprivate.Api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tfprivate-api:latest
